<a href="https://colab.research.google.com/github/bdfd/test-1/blob/master/Tut_16_Filling_up_the_NA_values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Filling up the NA Value

In [2]:
import urllib.request
import pandas as pd
import numpy as np

In [3]:
# @title
url = 'https://github.com/bdfd/Awesome_Dataset_Colltector/blob/main/dataset%20collection/2.0%20youtube/Python%20Pandas_Data%20Science%20Tutorials/Sample%20-%20Superstore%20Sales.xls?raw=true'
filename = 'Super_Store_Sales.xls'
urllib.request.urlretrieve(url, filename)

('Super_Store_Sales.xls', <http.client.HTTPMessage at 0x7d7d477c8280>)

In [ ]:
df = pd.read_excel('Super_Store_Sales.xls',0)

In [ ]:
df.head()

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Customer Name,Province,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
0,1,3,2010-10-13,Low,6,261.5400,0.04,Regular Air,-213.250,38.94,...,Muhammed MacIntyre,Nunavut,Nunavut,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,2010-10-20
1,2,6,2012-02-20,Not Specified,2,6.9300,0.01,Regular Air,-4.640,2.08,...,Ruben Dartt,Alberta,West,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Kleencut® Forged Office Shears by Acme United ...,Small Pack,0.55,2012-02-21
2,3,32,2011-07-15,High,26,2808.0800,0.07,Regular Air,1054.820,107.53,...,Liz Pelletier,Alberta,West,Corporate,Furniture,Office Furnishings,Tenex Contemporary Contur Chairmats for Low an...,Medium Box,0.65,2011-07-17
3,4,32,2011-07-15,High,24,1761.4000,0.09,Delivery Truck,-1748.560,70.89,...,Liz Pelletier,Alberta,West,Corporate,Furniture,Tables,KI Conference Tables,Jumbo Box,0.72,2011-07-16
4,5,32,2011-07-15,High,23,160.2335,0.04,Regular Air,-85.129,7.99,...,Liz Pelletier,Alberta,West,Corporate,Technology,Telephones and Communication,Bell Sonecor JB700 Caller ID,Medium Box,0.60,2011-07-17

In [ ]:
df.isnull()

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Customer Name,Province,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8385,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8386,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8387,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8388,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8389,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

Row ID                   0
Order ID                 0
Order Date               0
Order Priority           0
Order Quantity           0
Sales                    0
Discount                 0
Ship Mode                0
Profit                   0
Unit Price               0
Shipping Cost            0
Customer Name            0
Province                 0
Region                   0
Customer Segment         0
Product Category         0
Product Sub-Category     0
Product Name             0
Product Container        0
Product Base Margin     63
Ship Date                0
dtype: int64